title: "Free Joomla! Extensions"
description: >-
Joomla! is an awesome CMS, but some extensions are needed to make it easier for a niche site. 
This is my attempt at filling that gap, because we need to catch up to WordPress.
baseurl: ""
github_username: brettvac
author:
  name: "Brett Vachon"

google_analytics: "G-DP5DG417G7"
  
theme: "jekyll-theme-cayman"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
