title: 
# Google Analytics 4
analytics:
  measurement_id: "G-XXXXXXXXXX"  

theme: "jekyll-theme-midnight"

# Author info
author:
  name: "Brett Vachon"
analytics:
  measurement_id: "G-XXXXXXXXXX"  

# Plugins (if using any plugins)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
